### ISSUE TITLE
write.codemeta deletes all files on my computer

### ISSUE THREAD

**Issue by smccord** [ropensci/codemetar#242] opened 2019-08-20 13:58 UTC
This occurs when I am prompted to update the codemeta.json file after attempting a git commit

**Comment by cboettig** [comment] 2019-08-20 19:34
@smccord That's terrible! Thanks for filing the bug report.  Can you provide a bit more detail about your setup so we can look into this further?  We're not able to reproduce the behavior based on the description you provide.  From your twitter [comment](https://twitter.com/mccord_se/status/1163606324757667841?s=19), it sounds like it was all the files in your "My Documents" folder that got deleted?  `codemeta::write_codemeta()` doesn't attempt to delete anything, so we are perplexed why this would happen.  Can you let us know:

- What version of codemeta you are running? (just paste the output of `sessionInfo()` into the issue thread here, that will give us more detail).
- Is your git repository root directory (where you are writing the codemeta.json file) the `My Documents` folder itself, or is it in a folder inside that folder?
- What happens if you try this in a different location outside of My Documents?  e.g. you might try:

```r
library(magrittr)
library(rstudioapi)

tempdir() %>%  initializeProject() %>% openProject(TRUE)
```

to create a new project in RStudio, and then see if you can reproduce the behavior there.  (This will be in a temporary working directory that isn't in your My Documents directory).  

Also, can you try to reproduce the behavior using the current development version?  Run `remotes::install_github("ropensci/codemetar")` and restart your R session to test.

**Comment by smccord** [comment] 2019-08-20 23:07
Thanks for getting back to me! I've now wiped all traces of codemetar to
double confirm that was the culprit (it is--somehow!), so it'll take me a
minute to reproduce it again for you, but I'll try to do that and let you
know.

**Comment by smccord** [comment] 2019-10-02 16:38
Thanks for your help. I think I've traced it back to a bad temp directory or  inst/doc location. I'm re-creating the package now--so hopefully this is behind us!

https://github.com/r-lib/pkgbuild/issues/58

**Comment by maelle** [comment] 2019-11-13 11:11
@smccord so should something be changed in codemetar? docs? Thanks in advance.

**Comment by smccord** [comment] 2019-11-13 15:05
I'm not sure--I think it has something to do with where the temp directory
is set for your R environment? But I haven't been able to intentionally
replicate, just unintentionally.

**Comment by maelle** [comment] 2019-11-20 12:33
@cboettig what should we do here, is there anything we could/should document?

**Comment by cboettig** [comment] 2019-11-20 16:16
@maelle I think we should close this.  It is possibly related to the user moving the temp directory around, some software may assume it can clear out the temp directory (though we don't change temp directory in `codemetar`, and R doesn't clear temp directory unless you make it...)  

I know it sounds like a really scary issue, but I cannot see how it is connected to codemetar and we cannot reproduce it.  I think leaving this thread on the issues is sufficient documentation, since we can't say anything more definitive about this.

**Closed by cboettig** 2019-11-20 16:16 UTC
