### ISSUE TITLE
failing test

### ISSUE THREAD

**Issue by cboettig** [ropensci/codemetar#155] opened 2018-05-03 22:01 UTC
@maelle 

This test is failing for me: 

https://github.com/ropensci/codemetar/blob/4ab555a61ee42b046412089bf641f34f0e95f9de/tests/testthat/test-write_codemeta.R#L48-L55

Gets back `NULL` instead of expected result.  Any ideas?

Also, shouldn't  we also `skip_on_cran()` anything that we `skip_on_travis()`?

**Comment by maelle** [comment] 2018-05-04 02:31
I cannot see any obvious problem in https://github.com/ropensci/codemetar/blob/7ce13ba50a439b7b9accd8b694bd486c23685384/R/create_codemeta.R#L101

**Comment by cboettig** [comment] 2018-05-04 03:26
ok, we can investigate later. I've turned off this check for cran, winbuilder check still is OK, so I posted the 1.6 release.  🤞 , Thanks for adding all the awesome! 🚀 :sparkles:

**Comment by maelle** [comment] 2018-05-04 04:18
Yay good luck codemetar!

I might add Travis buils for Mac. 

And a few questions to investigate:

Do you get a CRAN relatedLink for other packages? Did you install usethis from CRAN?

**Comment by maelle** [comment] 2018-05-04 04:25
It might be due to linebreaks in the README 🤔

Do you know why knitting a README can lead to linebreaks in badges? Which are fine for displaying but not fine for parsing? https://raw.githubusercontent.com/r-lib/usethis/master/README.md I was a bit stupid here I guess bc instrad of investigating I decided to use README.Rmd rather than README.md to parse badges when present but sometimes we only have a README.md originating from README.Rmd and thus do not get badges.

**Comment by cboettig** [comment] 2018-05-04 04:29
yup, I did install from CRAN, and I confirmed I get the error for other packages (I tested `stringi`), though it works for `codemetar`.  

Re linebreaks, maybe I think knitr or pandoc is adding them in an attempt to enforce a maximum line length?  Are we grepping the alt-text to find the badges?  wouldn't it be better to grep the urls, which don't get broken across lines anyway?

**Comment by maelle** [comment] 2018-05-04 04:31
Mmmh weird what does pkgsession return for these pkgs?

We parse the whole badges thanks to a regexp. I think I just need to improve it to allow linebreaks see extract_badges function.

**Comment by cboettig** [comment] 2018-05-04 04:40
Right, but I wonder if it would be better for the regex to just target the url -- not sure if the alt-text is always 100% consistent (i.e. you can change the alt-text and still get the same badge, but a URL is URL).

**Comment by maelle** [comment] 2018-05-07 09:15
@cboettig I made the two changes mentioned above (using the URL instead of the alt text, making the parsing robust to line breaks) but I'm not sure it'll fix the test. Could you please write the output of

```r
pkg_info <- sessioninfo::package_info("usethis")
pkg_info <- pkg_info[pkg_info$package == "usethis",]
pkg_info 
pkg_info$source
```

**Comment by maelle** [comment] 2018-05-07 09:41
Now I can reproduce the bug on Travis, but there I'm not sure whether it's actually a bug or whether packages are installed from a local source.

**Comment by maelle** [comment] 2018-05-28 08:35
@cboettig could you tell me what you get when running

```r
pkg_info <- sessioninfo::package_info("usethis")
pkg_info <- pkg_info[pkg_info$package == "usethis",]
pkg_info 
pkg_info$source
```

I had started exploring in the 155 branch (that I'll delete since some of the commits are useless now).

**Comment by cboettig** [comment] 2018-11-06 17:19
I see

```
> library(codemetar)
> pkg_info <- sessioninfo::package_info("usethis")
> pkg_info <- pkg_info[pkg_info$package == "usethis",]
> pkg_info 
 package * version date       lib source        
 usethis   1.4.0   2018-08-14 [1] CRAN (R 3.5.0)

[1] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
> pkg_info$source
[1] "CRAN (R 3.5.0)"
> 
````

**Comment by maelle** [comment] 2018-11-06 17:29
And the test still fails, right?

**Comment by cboettig** [comment] 2018-11-06 17:49
ha, good question!  Nope, I cannot get the test to fail now.  Just tested on Mac & Linux and both are happy....

**Comment by maelle** [comment] 2018-11-06 18:14
Aha, then can we unskip and close this?

**Comment by cboettig** [comment] 2018-11-06 18:16
:+1: 

guess try on a branch and see if it passes...

**Closed** 2018-11-08 08:57 UTC
Labels: bug
